-- 02 · USERS — generated from lib/users.mjs (47 users) by scripts/generate-users-sql.mjs
-- generated-checksum: 7351f140d47442a4
--
-- ⚠ DO NOT EDIT THIS FILE BY HAND — add/remove users in lib/users.mjs, then run
--   node scripts/generate-users-sql.mjs   (it rebuilds this file from that list)
--
-- Makes the users table match lib/users.mjs exactly:
--   • adds new users and (re)sets every listed user's password
--   • DELETES users who are not in the list
--   • a removed user who has placed bids (or leads a table) is DEACTIVATED instead, so the
--     bid history stays intact — they can no longer log in
-- Passwords are bcrypt-hashed inside Postgres (pgcrypto), the format the login code checks.
-- Safe to re-run. To add or remove someone: edit lib/users.mjs, run
-- node scripts/generate-users-sql.mjs, then run this file in the Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

BEGIN;

INSERT INTO users (username, password_hash, is_active)
SELECT username, extensions.crypt(password, extensions.gen_salt('bf', 10)), true
FROM (VALUES
  ('luckymahajan', 'luckymahajan1356'),
  ('mansidongre', 'mansidongre9695'),
  ('durvadhargalkar', 'durvadhargalkar2080'),
  ('shoaibtamboli', 'shoaibtamboli3345'),
  ('gauravwathore', 'gauravwathore3081'),
  ('anayaraina', 'anayaraina3506'),
  ('yashkhandelwal', 'yashkhandelwal4311'),
  ('kshitijaanandrao', 'kshitijaanandrao3997'),
  ('pravinraut', 'pravinraut8672'),
  ('ankithemnani', 'ankithemnani8580'),
  ('ravindra', 'ravindra9651'),
  ('amargaikwad', 'amargaikwad4656'),
  ('bhusan', 'bhusan2949'),
  ('jayesh', 'jayesh3042'),
  ('sunnymaan', 'sunnymaan4830'),
  ('abdulkhan', 'abdulkhan8888'),
  ('gauravchindhe', 'gaurav'),
  ('prathameshjoshi', 'prathamesh6969'),
  ('devanshuthite', 'devanshuthite8205'),
  ('mridul', 'mridul4821'),
  ('onkarsolanke', 'onkarsolanke4575'),
  ('samek', 'samek5950'),
  ('akhileshsharma', 'akhileshsharma3677'),
  ('vishalmarne', 'vishalmarne6441'),
  ('dhirajpatil', 'dhirajpatil4077'),
  ('ketanmane', 'ketanmane7645'),
  ('manishbansal', 'manishbansal6672'),
  ('sanketdigrase', 'sanketdigrase6831'),
  ('karanbhangire', 'karanbhangire9887'),
  ('piyushpatil', 'piyushpatil6674'),
  ('vaishnavlimaya', 'vaishnavlimaya5403'),
  ('vishalnawale', 'vishalnawale2330'),
  ('karanthakur', 'karanthakur6322'),
  ('ankitsehgal', 'ankitsehgal1897'),
  ('nileshruptakke', 'nileshruptakke4236'),
  ('anuragbhatt', 'anuragbhatt5910'),
  ('shrirajkarpi', 'shrirajkarpi2606'),
  ('amanshaikh', 'amanshaikh3574'),
  ('abhishekkusumbekar', 'abhishekkusumbekar8501'),
  ('dhurvkhopade', 'dhurvkhopade8569'),
  ('nitingosavi', 'nitingosavi7828'),
  ('abhithorat', 'abhithorat5027'),
  ('sopangaikwad', 'sopangaikwad9308'),
  ('sonalsharma', 'sonalsharma8456'),
  ('rupeshpatil', 'rupeshpatil3639'),
  ('karansharma', 'karansharma6572'),
  ('rajendrapurohit', 'rajendrapurohit1316')
) AS listed(username, password)
ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash, is_active = true;

-- Removed users with bid history: keep the row (bids point at it) but block login
UPDATE users SET is_active = false
WHERE username NOT IN ('luckymahajan', 'mansidongre', 'durvadhargalkar', 'shoaibtamboli', 'gauravwathore', 'anayaraina', 'yashkhandelwal', 'kshitijaanandrao', 'pravinraut', 'ankithemnani', 'ravindra', 'amargaikwad', 'bhusan', 'jayesh', 'sunnymaan', 'abdulkhan', 'gauravchindhe', 'prathameshjoshi', 'devanshuthite', 'mridul', 'onkarsolanke', 'samek', 'akhileshsharma', 'vishalmarne', 'dhirajpatil', 'ketanmane', 'manishbansal', 'sanketdigrase', 'karanbhangire', 'piyushpatil', 'vaishnavlimaya', 'vishalnawale', 'karanthakur', 'ankitsehgal', 'nileshruptakke', 'anuragbhatt', 'shrirajkarpi', 'amanshaikh', 'abhishekkusumbekar', 'dhurvkhopade', 'nitingosavi', 'abhithorat', 'sopangaikwad', 'sonalsharma', 'rupeshpatil', 'karansharma', 'rajendrapurohit')
  AND (id IN (SELECT user_id FROM bids WHERE user_id IS NOT NULL)
       OR id IN (SELECT highest_bidder_id FROM tables WHERE highest_bidder_id IS NOT NULL));

-- Removed users with no bids: delete
DELETE FROM users
WHERE username NOT IN ('luckymahajan', 'mansidongre', 'durvadhargalkar', 'shoaibtamboli', 'gauravwathore', 'anayaraina', 'yashkhandelwal', 'kshitijaanandrao', 'pravinraut', 'ankithemnani', 'ravindra', 'amargaikwad', 'bhusan', 'jayesh', 'sunnymaan', 'abdulkhan', 'gauravchindhe', 'prathameshjoshi', 'devanshuthite', 'mridul', 'onkarsolanke', 'samek', 'akhileshsharma', 'vishalmarne', 'dhirajpatil', 'ketanmane', 'manishbansal', 'sanketdigrase', 'karanbhangire', 'piyushpatil', 'vaishnavlimaya', 'vishalnawale', 'karanthakur', 'ankitsehgal', 'nileshruptakke', 'anuragbhatt', 'shrirajkarpi', 'amanshaikh', 'abhishekkusumbekar', 'dhurvkhopade', 'nitingosavi', 'abhithorat', 'sopangaikwad', 'sonalsharma', 'rupeshpatil', 'karansharma', 'rajendrapurohit')
  AND id NOT IN (SELECT user_id FROM bids WHERE user_id IS NOT NULL)
  AND id NOT IN (SELECT highest_bidder_id FROM tables WHERE highest_bidder_id IS NOT NULL);

COMMIT;

-- Check: who can log in now
SELECT username, is_active FROM users ORDER BY is_active DESC, username;
