export const USERS = [
  { username: "GauravChindhe", password: "37gaurav" },
  { username: "AbhayYadav", password: "45abhay" },
  { username: "PrathameshJoshi", password: "66prathamesh" },
  { username: "Manavkhiani", password: "manavxti1" },
  { username: "SunnySinghMann", password: "sunnyxmeraki01" },
  { username: "NikhilShinde", password: "32nikhilking" },
{ username: "AkashShirodkar", password: "555akashking" },
{ username: "RohitJadhav", password: "556rohitking" },
{ username: "HarshPorwal", password: "84harshking" },
{ username: "DhruvKhopade", password: "557dhruvking" },
{ username: "TusharChaudhary", password: "89tusharking" },
{ username: "AmanTamhane", password: "558amanking" },
{ username: "KunalChavan", password: "559kunalking" },
{ username: "SahilDoshi", password: "560sahilking" },
{ username: "AryanDoshi", password: "561aryanking" },
{ username: "RajSuryawanshi", password: "562rajking" },
{ username: "DarshanParekh", password: "563darshanking" },
{ username: "AtharvaDarade", password: "33atharvaking" },
{ username: "ShaunakApte", password: "79shaunanking" },
{ username: "RohitJadhav", password: "556rohitking" },
{ username: "SuhasGaikwad", password: "564suhasking" },
{ username: "RishiBagade", password: "565rishiking" },
{ username: "AdityaTrivedi", password: "566adityaking" },
{ username: "ShubhamKale", password: "567shubhamking" }
];
