// Bidding users. After editing, regenerate scripts/sql/02-seed-users.sql and run it in Supabase.
// name is for your reference only — the database stores username + a bcrypt hash of the password.
export const USERS = [
  { name: "Lucky Mahajan", username: "luckymahajan", password: "luckymahajan1356" },
  { name: "Mansi Dongre", username: "mansidongre", password: "mansidongre9695" },
  { name: "Durva Dhargalkar", username: "durvadhargalkar", password: "durvadhargalkar2080" },
  { name: "Shoaib Tamboli", username: "shoaibtamboli", password: "shoaibtamboli3345" },
  { name: "Gaurav Wathore", username: "gauravwathore", password: "gauravwathore3081" },
  { name: "Anaya Raina", username: "anayaraina", password: "anayaraina3506" },
  { name: "Yash Khandelwal", username: "yashkhandelwal", password: "yashkhandelwal4311" },
  { name: "Kshitija Anandrao", username: "kshitijaanandrao", password: "kshitijaanandrao3997" },
  { name: "Pravin Raut", username: "pravinraut", password: "pravinraut8672" },
  { name: "Ankit Hemnani", username: "ankithemnani", password: "ankithemnani8580" },
  { name: "Ravindra Mebhi", username: "ravindra", password: "ravindra9651" },
  { name: "Amar Gaikwad", username: "amargaikwad", password: "amargaikwad4656" },
  { name: "Bhushan Choudhary", username: "bhusan", password: "bhusan2949" },
  { name: "Jayesh Chive", username: "jayesh", password: "jayesh3042" },
  { name: "Sunny Maan", username: "sunnymaan", password: "sunnymaan4830" },
  { name: "Abdul Khan", username: "abdulkhan", password: "abdulkhan8888" },
  { name: "Gaurav Chindhe", username: "gauravchindhe", password: "gaurav" },
  { name: "Prathamesh Joshi", username: "prathameshjoshi", password: "prathamesh6969" },
  { name: "Devanshu Thite", username: "devanshuthite", password: "devanshuthite8205" },
  { name: "Mridul", username: "mridul", password: "mridul4821" },

  { name: "Onkar Solanke", username: "onkarsolanke", password: "onkarsolanke4575" },
  { name: "Samek", username: "samek", password: "samek5950" },
  { name: "Akhilesh Sharma", username: "akhileshsharma", password: "akhileshsharma3677" },
  { name: "Vishal Marne", username: "vishalmarne", password: "vishalmarne6441" },
  { name: "Dhiraj Patil", username: "dhirajpatil", password: "dhirajpatil4077" },
  { name: "Ketan Mane", username: "ketanmane", password: "ketanmane7645" },
  { name: "Manish Bansal", username: "manishbansal", password: "manishbansal6672" },
  { name: "Sanket Digrase", username: "sanketdigrase", password: "sanketdigrase6831" },
  { name: "Karan Bhangire", username: "karanbhangire", password: "karanbhangire9887" },
  { name: "Piyush Patil", username: "piyushpatil", password: "piyushpatil6674" },
  { name: "Vaishnav Limaya", username: "vaishnavlimaya", password: "vaishnavlimaya5403" },
  { name: "Vishal Nawale", username: "vishalnawale", password: "vishalnawale2330" },
  { name: "Karan Thakur", username: "karanthakur", password: "karanthakur6322" },
  { name: "Ankit Sehgal", username: "ankitsehgal", password: "ankitsehgal1897" },
  { name: "Nilesh Ruptakke", username: "nileshruptakke", password: "nileshruptakke4236" },
  { name: "Anurag Bhatt", username: "anuragbhatt", password: "anuragbhatt5910" },
  { name: "Shriraj Karpi", username: "shrirajkarpi", password: "shrirajkarpi2606" },
  { name: "Aman Shaikh", username: "amanshaikh", password: "amanshaikh3574" },
  { name: "Abhishek Kusumbekar", username: "abhishekkusumbekar", password: "abhishekkusumbekar8501" },
  { name: "Dhurv Khopade", username: "dhurvkhopade", password: "dhurvkhopade8569" },
  { name: "Nitin Gosavi", username: "nitingosavi", password: "nitingosavi7828" },
  { name: "Abhi Thorat", username: "abhithorat", password: "abhithorat5027" },
  { name: "Sopan Gaikwad", username: "sopangaikwad", password: "sopangaikwad9308" },
  { name: "Sonal Sharma", username: "sonalsharma", password: "sonalsharma8456" },
  { name: "Rupesh Patil", username: "rupeshpatil", password: "rupeshpatil3639" },
  { name: "Karan Sharma", username: "karansharma", password: "karansharma6572" },
  { name: "Rajendra Purohit", username: "rajendrapurohit", password: "rajendrapurohit1316" },
  { name: "Santosh Oswal", username: "santoshoswal", password: "santoshoswal1316" },
]
